config/routes.rb
Rails.application.routes.draw do
  get 'play/index'

  resources :games
   root 'play#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
					  

	 before_create :random

	 def random
	 	self.answer = rand(1..10)	
	 end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	
	def index
		@games = Game.all
	end

	def new
		@game = Game.create


		redirect_to @game
	end
	
	def show
  		@game = Game.find(params[:id])
  		@guess = guess
  		
	end

	def update
		@game = Game.find(params[:id])
		@game.guess_count += 1
		@guess = guess
		@game.save
			
  		
		render 'games/show'
		
	end

	def destroy
		@game = Game.find(params[:id])
		@game.destroy

		redirect_to games_path
	end



	private
		def guess
			params[:guess] 
		end
end

app/controllers/play_controller.rb
class PlayController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/play_helper.rb
module PlayHelper
end

app/views/games/_form.html.erb
<%= form_for @game do |f| %>
 <p> 
 	<% if @game.guess_count == 0 %>
 		<%= f.label :guess, "Guess" %>
 	<% else %>
  		<%= f.label :guess, "Try Again!" %><br>
 	 <% end %>
  <%= text_field_tag :guess %>
 </p>
 <p>
  <%= f.submit %>
 </p>
<% end %>

app/views/games/index.html.erb
<head> 
  <link type="text/css" rel="stylesheet" href="games.css.scss"/>
</head>
<h1> Listing Games! </h1>
<table>
  <tr>
    <th>Answer</th>
    <th>Guesses</th>
    <th colspan="3"></th>
  </tr>
 
  <% @games.each do |game| %>
    <tr>
      <td><%= game.answer %></td>
      <td><%= game.guess_count %></td>
      <td><%= link_to 'Play', game_path(game) %></td>
      <td><%= link_to 'Delete', game_path(game),
                      method: :delete, data: { confirm: 'Are you sure?'
} %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New Game', new_game_path %>

app/views/games/show.html.erb
<head>
	<link type="text/css" rel="stylesheet" href="games.css.scss"/>
</head>
<% if @game.guess_count == 0 %>
<h1> Guess a number from 1 to 10 </h1>
<% else %>
<h1>Guess</h1>
<% if @guess.blank? %>
<% x = "Your need to enter a guess" %>
<% elsif @guess.to_i > @game.answer %>
<% x = "#{@guess} is too High"%>
<% elsif @guess.to_i < @game.answer %>
<% x = "#{@guess} is too Low" %>
<% else %>
<% x = "You guessed right!" %>
<% end %>
<% end %>
<% if @game.guess_count > 0 %>
You have made <%= @game.guess_count %> guesses.
<% end %>
<p>
  <strong>Your Guess:</strong><br>
  <%= x %>
</p>


<% if @guess.blank? || @guess.to_i != @game.answer %>
<%= render 'form' %>
<% else %>
<%= link_to "Play Again", new_game_path %>
<% end %>
<%= link_to 'Games', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Guess</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/play/index.html.erb
<head> 
	<link type="text/css" rel="stylesheet" href="play.css.scss"/>
</head>
<body>
	<div class="instructions">
	<h1 id="fancy">Guess?</h1>
		<p class="paragraph">Guess is a game where you, the user, guess what number I'm thinking of.</p>
		<p>The number I'm thinking of is somewhere from 1 to 10</p>
		<p class="paragraph">I will tell you whether your number is too high or low until you guess it right</p>
		<p>Click the link to play!</p> 
	</div>
		<%= link_to 'Play Guess!', new_game_path %>
</body>